<?php
$objLeilao = new ItemLeilao();
?>
<div class="container pt-3 pb-3">
    <div class="row">

        <div class="d-md-none d-block p-3 w-100">
            <div class="btn-group d-block w-100" role="group">
                <div class="btn-group d-block w-100" role="group">
                    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle btn-block" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?= lang('CATEGORIAS') ?>
                    </button>
                    <div class="dropdown-menu w-100">
                        <?php
                        foreach ($topo_lotes1_cate as $key => $value) {
                            ?>
                            <a class="dropdown-item" href="<?= busca_url('cate[]=' . $value->id) ?>">
                                <?= $value->nome ?>
                            </a>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="list-group col-3 d-md-block d-none">
            <?php
            $list = array();
            foreach ($topo_lotes1_cate_star as $key => $value) {
                array_push($list, $value->id);
                ?>
                <a href="<?= busca_url('cate[]=' . $value->id) ?>" class="list-group-item list-group-item-action  d-flex justify-content-between align-items-center">
                    <?= $value->nome ?>
                    <span class="badge badge-primary badge-pill"><?= qtd_itens($value->id, 'categorias') ?> </span>
                </a>
                <?php
            }
            ?>
            <a data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center dropdown-toggle">
                <?= lang('Veja mais'); ?>

            </a>

            <div class="dropdown-menu">
                <?php
                foreach ($topo_lotes1_cate as $key => $value) {
                    if (!in_array($value->id, $list)) {
                        ?>
                        <a class="dropdown-item d-flex justify-content-between align-items-center" href="<?= busca_url('cate[]=' . $value->id) ?>">
                            <?= $value->nome ?>
                            <!--span class="badge badge-primary badge-pill"><?= qtd_itens($value1->id, 'categorias') ?></span-->

                        </a>
                        <?php
                    }
                }
                ?>
            </div>
        </div>

        <div class="col-md-9 pr-0">
            <div id="carousel" class="carousel slide" data-ride="carousel" data-interval="8000">
                <ol class="carousel-indicators">
                    <?php
                    $i = 0;
                    foreach ($banner as $k => $b) {
                        foreach ($b as $key => $value) {
                            ?>
                            <li style="background-color: #007bff;" data-target="#" data-slide-to="<?= $key ?>" class="<?= ($i == 0) ? 'active' : ''; ?>"></li>
                            <?php
                            $i++;
                        }
                    }
                    ?>
                </ol>
                <div class="carousel-inner">

                    <?php
                    $i = 0;
                    foreach ($banner as $k => $b) {
                        foreach ($b as $key => $value) {
                            ?>
                            <div class="carousel-item <?= ($i == 0) ? 'active' : ''; ?>">
                                <a <?= $value->link ? 'href="' . http($value->link) . '"' : '' ?>>
                                    <img style="max-height: 395px;border-radius: 10px;" class="d-block w-100" src="/web/fotos/<?= $value->foto ?>" alt="<?= $value->nome ?>">
                                </a>
                            </div>
                            <?php
                            $i++;
                        }
                    }
                    ?>

                </div>
                <a class="carousel-control-prev text-primary" href="#carousel" role="button" data-slide="prev">
                    <i class="fa fa-arrow-circle-left"></i>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next text-primary" href="#carousel" role="button" data-slide="next">
                    <i class="fa fa-arrow-circle-right"></i>
                    <span class="sr-only">Next</span>
                </a>
            </div>

        </div>
    </div>
</div>
<!-- ######################### -->
<?php $leiloes_e_lotes_home = 1 ?>
<?php if ($leiloes_e_lotes_star) { ?>
    <div class="container p-2">

        <div class="row justify-content-between align-items-center">
            <h2>LOTES EM DESTAQUE</h2>
            <div style="background-color: var(--primary-color);height: 8px;width: 100%;"></div>
        </div>

        <div class="row">
            <?php
            $tipo_box = 'star';
            foreach ($leiloes_e_lotes_star as $key => $value) {

                if ($value->table == 'lotes') {
                    include 'item_leilao.phtml';
                }
            }
            ?>
        </div>
    </div>
<?php } ?>

<!-- ######################### -->
<?php
$tipo_box = 'normal';
if ($leiloes) {
    $tipo = 'lotes';
    ?>
    <div class="container p-2">

        <div class="row justify-content-between align-items-center">
            <h2>PRÓXIMOS LEILÕES</h2>
            <div style="background-color: var(--primary-color);height: 8px;width: 100%;"></div>
        </div>

        <div class="row">
            <?php
            foreach ($leiloes as $key => $value) {

                include 'item_leilao.phtml';
            }
            ?>
        </div>
    </div>
<?php } ?>


<!-- ######################### -->
<?php /*
  if ($leiloes_arrematados) {

  $leiloes_e_lotes_home = 1;
  $lotes_arrematados_home = 1;
  $tipo = 'lotes';
  ?>
  <div class="container p-2">

  <div class="row justify-content-between align-items-center">
  <h2>LEILÕES ENCERRADOS</h2>
  <div style="background-color: var(--primary-color);height: 8px;width: 100%;"></div>
  </div>

  <div class="row">
  <?php
  foreach ($leiloes_arrematados as $key => $value) {

  include 'item_leilao.phtml';
  }
  ?>
  </div>
  </div>
  <?php } */ ?>


<!-- ######################### -->
<?php
if ($lotes_arrematados) {
    $tipo = 'lote';
    $lotes_arrematados_home = 1;
    ?>
    <div class="container p-2">

        <div class="row justify-content-between align-items-center">
            <h2>LOTES ARREMATADOS</h2>
            <div style="background-color: var(--primary-color);height: 8px;width: 100%;"></div>
        </div>

        <div class="row">
            <?php
            foreach ($lotes_arrematados as $key => $value) {
                include 'item_leilao.phtml';
            }
            ?>
        </div>
    </div>
<?php } ?>