<?php

$sql = $mysql->db->prepare("SELECT valor FROM configs WHERE id = 25");
$sql->execute();
$reg = $sql->fetch(PDO::FETCH_ASSOC);

$dados = unserialize($reg['valor']);

if ($_GET['nome'] == 'recibo_provisorio') {
    $mysql->prepare = array($_GET['id']);
    $mysql->filtro = " WHERE id = ? AND situacao = 2 ";
    $lotes = $mysql->read_unico('lotes');
    //$frete = $mysql->read_unico('frete');
} elseif ($_GET['nome'] == 'termo_arrematacao') {
    $mysql->prepare = array($_GET['id']);
    $mysql->filtro = " WHERE id = ? AND pago = 1 AND situacao = 2 ";
    $lotes = $mysql->read_unico('lotes');
} elseif ($_GET['nome'] == 'nota1') {
    $url = DIR_C . DIR_D;
    $url = isset($_GET['emitir_nota_txt']) ? str_replace($_GET['emitir_nota_txt'], base64_encode($_GET['emitir_nota_txt']), $url) : '';
    $url = str_replace('/imprimir/nota1/?', '/imprimir/nota/?', $url);
    location($url);
} elseif ($_GET['nome'] == 'nota') {
    $ids = array(0);
    $ex = explode('-', $_GET['ids']);
    foreach ($ex as $key => $value) {
        if ($value) {
            $ids[] = $value;
        }
    }
    $mysql->filtro = " WHERE id IN (" . implode(',', $ids) . ") AND pago = 1 AND situacao = 2 ";
    $lotes = $mysql->read('lotes');
} elseif ($_GET['nome'] == 'etiqueta') {
    $ids = array(0);
    $ex = explode('-', $_GET['ids']);
    foreach ($ex as $key => $value) {
        if ($value) {
            $ids[] = $value;
        }
    }
    $mysql->filtro = " WHERE id IN (" . implode(',', $ids) . ") ";
    $lotes = $mysql->read('lotes');
}

$mysql->filtro = " WHERE `tipo` = 'info_termos_e_notas' ";
$info_termos_e_notas = $mysql->read_unico('configs');



if (isset($lotes->id) or isset($lotes[0]->id)) {

    $lote = isset($lotes->id) ? $lotes : $lotes[0];

    $mysql->prepare = array($lote->lances_cadastro);
    $mysql->filtro = " WHERE id = ? ";
    $cadastro = $mysql->read_unico('cadastro');
    //Frete
    $frete = $mysql->read_unico('frete');
    //if(strcasecmp($frete->estado,$cadastro->estados)){	
    //$valor_frete = $frete->valor_frete;	
    //} 

    switch ($cadastro->estados) {
        case 'AC':
            $valor_frete = '0';
            break;
        case 'AL':
            $valor_frete = '0';
            break;
        case 'AP':
            $valor_frete = '0';
            break;
        case 'AM':
            $valor_frete = '0';
            break;
        case 'BA':
            $valor_frete = '0';
            break;
        case 'CE':
            $valor_frete = '0';
            break;
        case 'DF':
            $valor_frete = '0';
            break;
        case 'ES':
            $valor_frete = '0';
            break;
        case 'GO':
            $valor_frete = '0';
            break;
        case 'MA':
            $valor_frete = '0';
            break;
        case 'MT':
            $valor_frete = '0';
            break;
        case 'MS':
            $valor_frete = '0';
            break;
        case 'MG':
            $valor_frete = '0';
            break;
        case 'PA':
            $valor_frete = '0';
            break;
        case 'PB':
            $valor_frete = '0';
            break;
        case 'PR':
            $valor_frete = '0';
            break;
        case 'PE':
            $valor_frete = '0';
            break;
        case 'PI':
            $valor_frete = '0';
            break;
        case 'RJ':
            $valor_frete = '0';
            break;
        case 'RN':
            $valor_frete = '0';
            break;
        case 'RS':
            $valor_frete = '0';
            break;
        case 'RO':
            $valor_frete = '0';
            break;
        case 'RR':
            $valor_frete = '0';
            break;
        case 'SC':
            $valor_frete = '0';
            break;
        case 'SP':
            $valor_frete = '0';
            break;
        case 'SE':
            $valor_frete = '0';
            break;
        case 'TO':
            $valor_frete = '0';
            break;
    }

    if (isset($_SESSION['x_admin']->id) or (isset($_SESSION['x_site']->id) and $_SESSION['x_site']->id == $cadastro->id)) {
?>

        <div style="<?= $_GET['nome'] == 'etiqueta' ? 'width: 600px; border: 0;' : 'width: 800px; border: 2px solid #666;' ?> padding: 1px; margin: 20px auto; font-size: 12px; font-family: Arial, Helvetica, sans-serif;">

            <?php if ($_GET['nome'] != 'etiqueta') { ?>
                <table cellpadding="0" cellspacing="0" border="1" style="width:100%">
                    <tr>
                        <td style="text-align: center; border-right: 0">
                            <div style="padding-top: 10px"><img src="<?= DIR_C ?>/web/img/z_leilao/logo.png"" style=" max-width:200px;"></div>
                        </td>
                        <td rowspan="2" style="text-align: center; border-left: 0; border-right: 0">
                            <div style="font-size:20px; font-weight:bold"> <?= $dados['nome_empresa'] ?> </div>
                            <div style="font-size:12px; font-weight:bold"></div>
                            <div style="font-size:11px">Responsável Financeiro:<br><?= $dados['financeiro'] ?></div>
                            <div style="font-size:11px">CNPJ: <?= $dados['cnpj'] ?></div>
                            <div style="font-size:11px;">Endereço Escritório:</div>
                            <div style="font-size:11px"><?= $dados['endereco'] ?></div>
                            <div style="font-size:11px">CEP: <?= $dados['cep'] ?></div>
        </div>
        <!--div style="font-size:11px">Jardim Novo Mundo, Sorocaba-SP</div>

        <div style="font-size:11px">Parque Novo Mundo<br> São Paulo/SP CEP: 02180-040</div-->
        </div>
        <div style="font-size:11px">Telefone (11) 4113-6869</div>
        <div style="font-size:11px; font-weight:bold">www.ishikawaleiloes.com</div>
        </td>
        <td rowspan="2" style="text-align: center; border-left: 0">
            <div style="font-size:24px; font-weight:bold">
                <?php if ($_GET['nome'] == 'recibo_provisorio') { ?>
                    <div style="padding: 5px 0;">
                        TERMO<br> DE ARREMATAÇÃO
                    </div>
                    <div style="padding-bottom: 5px; font-size: 16px"><b>EMISSÃO: <?= data($lote->lances_data) ?></b></div>
                <?php } elseif ($_GET['nome'] == 'termo_arrematacao') { ?>
                    <div style="padding: 20px 0 12px;">
                        TERMO DE<br> ARREMATAÇÃO
                    </div>
                    <div style="padding-bottom: 8px; font-size: 16px"><b>EMISSÃO: <?= $lote->emissao ? $lote->emissao : data($lote->lances_data) ?></b></div>
                <?php } elseif ($_GET['nome'] == 'nota') { ?>
                    <div style="padding: 20px 0 12px;">
                        NOTA DE<br> VENDA <br>
                    </div>
                    <div style="padding-bottom: 8px; font-size: 16px"><b>EMISSÃO: <?= $lote->emissao ? $lote->emissao : data($lote->lances_data) ?></b></div>
                <?php } ?>
            </div>
        </td>
        </tr>
        </table>
    <?php } ?>

    <?php if ($_GET['nome'] == 'recibo_provisorio') { ?>
        <div style="height: 20px"></div>
        <table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
            <tr>
                <td colspan="2"><b>Lote(s):</b> <?= $lote->nome ?></td>
                <td colspan="2"><b>Data do Leilão:</b> <?= data($lote->lances_data) ?></td>
            </tr>
            <tr>
                <td colspan="2"><b>Arrematante:</b> <?= $cadastro->nome ?></td>
                <td colspan="2"><b>CPF/CNPJ:</b> <?= $cadastro->tipo ? $cadastro->cnpj : $cadastro->cpf ?></td>
            </tr>
            <tr>
                <td colspan="2"><b>Rua/Av:</b> <?= $cadastro->rua ?></td>
                <td><b>Nº:</b> <?= $cadastro->numero ?></td>
                <td><b>Compl.:</b> <?= $cadastro->complemento ?></td>
            </tr>
            <tr>
                <td><b>Bairro:</b> <?= $cadastro->bairro ?></td>
                <td><b>CEP:</b> <?= $cadastro->cep ?></td>
                <td colspan="2"><b>Cidade:</b> <?= $cadastro->cidades ?> / <?= $cadastro->estados ?></td>
            </tr>
            <tr>
                <td colspan="4"><b>Telefones:</b> <?= $cadastro->telefone ?> <?= $cadastro->celular ?></td>
            </tr>
        </table>

        <div style="height: 20px"></div>
        <?php $lances = array('lance' => 0, 'comissao' => 0, 'despesas' => 0); ?>
        <table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
            <tr>
                <td colspan="6" align="center"><b>RELAÇÃO DE LOTES</b></td>
            </tr>
            <tr>
                <td><b>LOTE</b></td>
                <td><b>VL. ARREMATADO</b></td>
                <td><b>COMISSÃO (5%)</b></td>
                <td><b>FRETE</b></td>
                <td><b>TOTAL</b></td>
                <td><b>SITUAÇÃO</b></td>
            </tr>
            <!-- Nao tem foreach pq eh so 1, mais ja ta ponto para o oreach -->
            <?
            $comissao_porc = $info_termos_e_notas->valor;
            if ($lote->comissao) {
                $comissao_porc = $lote->comissao;
            }
            $comissao_valor = $lote->lances * $comissao_porc / 100;
            ?>
            <tr>
                <td><?= (int) $lote->ordem ?></td>
                <td>
                    <?= preco($lote->lances, 1) ?>
                    <?php $lances['lance'] += $lote->lances ?>
                </td>
                <td>
                    <?= preco(($comissao_valor), 1) ?>
                    <?php $lances['comissao'] += $comissao_valor ?>
                </td>
                <td>
                    <?= preco($valor_frete, 1) ?>
                    <?php $valor_frete ?>
                </td>
                <td><?= preco($lote->lances + $comissao_valor + $valor_frete, 1) ?></td>
                <td>Arrematado</td>
            </tr>
            <tr>
                <td><b>TOTAL</b></td>
                <td><b><?= preco($lances['lance'], 1) ?></b></td>
                <td><b><?= preco($lances['comissao'], 1) ?></b></td>
                <td><b><?= preco($valor_frete, 1) ?></b></td>
                <td>
                    <b>
                        <?php $total = $lances['lance'] + $lances['comissao'] + $valor_frete ?>
                        <?= preco($total, 1) ?>
                    </b>
                </td>
                <td><b></b></td>
            </tr>
        </table>

        <div style="padding: 10px;">
            <div style="padding-top: 0px"><b>VALOR TOTAL DOS VENDIDOS:</b> <?= preco($total, 1) ?></div>
            <div style="padding-top: 2px"><b>VALOR TOTAL DOS CONDICIONAIS:</b> <?= preco(0, 1) ?></div>
            <div style="padding-top: 2px"><b>TOTAL GERAL:</b> <?= preco($total, 1) ?></div>
        </div>


        <div style="padding: 5px 10px 0; margin-top: 20px; font-size: 14px; border: 2px solid #666;">
            <div style="font-size: 22px; text-align: center;"><b>FORMA DE PAGAMENTO</b></div>

            <div style="padding-top: 2px"><b>O pagamento deverá ser feito impreterivelmente até as 16:00 horas do dia arremate. <br>
                    Depósito na conta corrente bancária abaixo em dinheiro, TED ou DOC.<br></b></div>


            <div style="padding-top: 15px"><b>Dados do Responsável Financeiro Ishikawa Leilões</b> </div>
            <div style="padding-top: 2px"><?= $dados['nome'] ?></div>
            <div style="padding-top: 2px"><b>CPF</b></div>
            <div style="padding-top: 2px"><?= $dados['cpf'] ?></div>
            <div style="padding-top: 2px"><b>Banco</b></div>
            <div style="padding-top: 2px"><?= $dados['banco'] ?></div>
            <div style="padding-top: 2px"><b>Agência</b></div>
            <div style="padding-top: 2px"><?= $dados['agencia'] ?></div>
            <div style="padding-top: 2px"><b>Conta Corrente</b></div>
            <div style="padding-top: 2px"><?= $dados['conta'] ?></div>


            <div style="padding-top: 15px; font-size: 18px"><b>VALOR TOTAL DO DEPÓSITO: <?= preco($total, 1) ?></b></div>
            <div style="padding-top: 2px; padding-bottom: 10px; font-size: 18px"><b>DATA LIMITE PARA DEPÓSITO:11/04/2019 até às 16:00.</b></div>


            <div style="padding-top: 2px"><b>Após o pagamento, o arrematante deverá nos enviar até as 16:00h do dia 11/04/2019 o comprovante de pagamento e solicitar a Nota de Venda via E-mail para financeiro@ishikawaleilao.com</b> </div>
            <br>
            <div style="padding-top: 18px"><b>Observações Importantes:</b><br></div><br>

            <div style="padding-top: 2px">No caso de depósitos através de DOC, a Nota de Venda somente será liberada no dia seguinte da data de depósito<br></div>
            <div style="padding-top: 2px">Não serão aceitos depósitos feitos em caixas eletrônicos, bem como depósitos em cheques (comuns ou administrativos).<br></div><br>
            <div style="padding-top: 2px">Os depósitos estarão sujeitos a confirmação mediante apresentação do comprovante do depósito com devida autenticação bancários dentro do prazo estabelecido, sob pena de perda de 20% do valor da arrematação em favor do comitente vendedor, bem como da comissão do leiloeiro, nos termos do artigo 418 do código civil brasileiro.<br></div>
            <br>
            <div style="padding-top: 18px"><b>Entrega do(s) Bem(ns)</b><br></div>
            <br>
            <div style="padding-top: 2px">O(s) bem(ns) arrematado(s) serão entregues somente após a integralização dos pagamentos. E a retirada dos mesmos deverá ser efetuada com a apresentação de documentação oficial e cópia deste E-mail no ato da entrega. <br>
                O prazo máximo de entrega do(s) lote(s) será de 03 (três) dias úteis contados a partir da data de realização do leilão.</div>


            <br><br><br>

        </div>


        <div style="padding: 35px 0 15px; font-size: 12px; text-align: center;">

            <div>ISHIKAWA LEILÕES<br>Patio Grupo 7, Rua: Laura Maiello Kook, N°1300, Jardim Novo Mundo,Sorocaba-SP<BR> CEP:18052-445</div>
        </div>


    <?php } elseif ($_GET['nome'] == 'termo_arrematacao') { ?>
        <div style="height: 20px">ois</div>
        <table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
            <tr>
                <?php $comitentes = rel('leiloes', $lote->leiloes, 'comitentes') ?>
                <td colspan="2"><b>COMITENTE:</b> <?= comitentes($comitentes) ?></td>
                <td colspan="2"><b>CPF/CNPJ:</b> <?= comitentes($comitentes, 'cpf_cnpj') ?></td>
            </tr>
            <tr>
                <td colspan="2"><b>DATA DO LEILÃO:</b> <?= data(rel('leiloes', $lote->leiloes, 'data'), 'd/m/Y H:i:s') ?></td>
                <td colspan="2"><b>Nº LEILÃO:</b> <?= rel('leiloes', $lote->leiloes, 'codigo') ?></td>
            </tr>
        </table>

        <div style="padding: 20px 10px 0">
            <b style="font-size: 24px">LOTE - <?= (int) $lote->ordem ?></b>
            <div style="padding-top: 5px"><?= txt($lotes) ?>dsadsa</div>
        </div>

        <div style="height: 20px"></div>
        <table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
            <tr>
                <td colspan="3" style="font-size: 22px"><b>VALOR DA ARREMATAÇÃO: <?= preco($lote->lances, 1) ?></b></td>
                <td style="font-size: 22px; text-align: center;"><b>Vendido</b></td>
            </tr>
            <tr>
                <td colspan="4"><b>Arrematante:</b> <?= $cadastro->nome ?></td>
            </tr>
            <tr>
                <td><b>CPF/CNPJ:</b> <?= $cadastro->tipo ? $cadastro->cnpj : $cadastro->cpf ?></td>
                <td><b>Telefones:</b> <?= $cadastro->telefone ?></td>
                <td colspan="2"><b>Celular:</b> <?= $cadastro->celular ?></td>
            </tr>
            <tr>
                <td colspan="2"><b>Rua/Av:</b> <?= $cadastro->rua ?></td>
                <td><b>Nº:</b> <?= $cadastro->numero ?></td>
                <td><b>Compl.:</b> <?= $cadastro->complemento ?></td>
            </tr>
            <tr>
                <td><b>Bairro:</b> <?= $cadastro->bairro ?></td>
                <td><b>CEP:</b> <?= $cadastro->cep ?></td>
                <td colspan="2"><b>Cidade:</b> <?= $cadastro->cidades ?> / <?= $cadastro->estados ?></td>
            </tr>
        </table>

        <div style="padding-top: 20px; text-align: center;">
            <b style="font-size: 22px">FORMA DE PAGAMENTO</b>
            <div style="font-size: 11px"><b>PAGAMENTOS DE ARREMATAÇÃO + COMISSÃO + TAXAS + DESPESAS</b></div>
        </div>

        <div style="padding: 20px 10px 0; font-size: 14px">
            <div style="padding-top: 0px"><b>Valor da Arrematação:</b> <?= preco($lote->lances, 1) ?></div>
            <div style="padding-top: 2px"><b>Valor da Comissão do leiloeiro:</b> <?= preco(($lote->lances * 5 / 100), 1) ?></div>
            <div style="padding-top: 2px"><b>Valor da Taxa:</b> <?= preco(0, 1) ?></div>
            <div style="padding-top: 2px"><b>Valor das Despesas:</b> <?= preco(0, 1) ?></div>
            <div style="padding-top: 2px; font-size: 20px"><b>Valor Total do Depósito: <?= preco($lote->lances + ($lote->lances * 5 / 100), 1) ?></b></div>
        </div>

        <div style="height: 20px"></div>
        <table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
            <tr>
                <td align="center" style="padding-top: 20px">
                    ____________________________________________
                    <div>ASSINATURA DO ARREMATANTE</div>
                </td>
                <td align="center">
                    <b>Confirmo o lance acima e declaro estar ciente<br> e de acordo com todas as condições<br> estabelecidas no catálogo e edital de leilão.</b>
                </td>
            </tr>
        </table>


    <?php } elseif ($_GET['nome'] == 'nota') { ?>
        <div style="height: 1px"></div>
        <table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
            <tr>
                <?php $comitentes = rel('leiloes', $lote->leiloes, 'comitentes') ?>
                <td colspan="2"><b>COMITENTE:</b> <?= comitentes($comitentes) ?></td>
                <td colspan="2"><b>CPF/CNPJ:</b> <?= comitentes($comitentes, 'cpf_cnpj') ?></td>
            </tr>
            <tr>
                <td colspan="2"><b>DATA DO LEILÃO:</b> <?= data(rel('leiloes', $lote->leiloes, 'data'), 'd/m/Y H:i:s') ?></td>
                <td colspan="2"><b>Nº LEILÃO:</b> <?= rel('leiloes', $lote->leiloes, 'codigo') ?></td>
            </tr>
            <tr>
                <td colspan="4"><b>Nome:</b> <?= $cadastro->nome ?></td>
            </tr>
            <tr>
                <td><b>CPF/CNPJ:</b> <?= $cadastro->tipo ? $cadastro->cnpj : $cadastro->cpf ?></td>
                <td><b>Telefones:</b> <?= $cadastro->telefone ?></td>
                <td colspan="2"><b>Celular:</b> <?= $cadastro->celular ?></td>
            </tr>
            <tr>
                <td colspan="2"><b>Rua/Av:</b> <?= $cadastro->rua ?></td>
                <td><b>Nº:</b> <?= $cadastro->numero ?></td>
                <td><b>Compl.:</b> <?= $cadastro->complemento ?></td>
            </tr>
            <tr>
                <td><b>Bairro:</b> <?= $cadastro->bairro ?></td>
                <td><b>CEP:</b> <?= $cadastro->cep ?></td>
                <td colspan="2"><b>Cidade:</b> <?= $cadastro->cidades ?> / <?= $cadastro->estados ?></td>
            </tr>
        </table>

        <?php $lance = 0; ?>
        <div style="height: 1px"></div>
        <table cellpadding="5" cellspacing="0" border="1" style="width:100%;">
            <tr>
                <td align="center" style="background: #f4f4f4"><b>LOTE</b></td>
                <td style="background: #f4f4f4"><b></b></td>
                <td align="center" style="background: #f4f4f4"><b>VALOR</b></td>
            </tr>
            <tr>
                <td colspan="3" style="padding: 0; border-top: 0"></td>
            </tr>
            <?
            for ($i = 1; $i <= 10; $i++) {
                if (count($lotes) < $i) {
                    $lotes[] = (object)array('ordem' => '', 'nome' => '&nbsp;', 'lances' => 0);
                }
            }
            ?>
            <?php foreach ($lotes as $key => $value) { ?>
                <tr>
                    <td align="center" style="width: 15%; border-top: 0; border-bottom: 0">
                        <div style="padding-bottom: 5px"><?= $value->ordem ? (int) $value->ordem : '' ?></div>
                    </td>
                    <td style="border-top: 0; border-bottom: 0">
                        <div style="padding-bottom: 5px"><?= $value->nome ?></div>
                    </td>
                    <td align="center" style="width: 30%; border-top: 0; border-bottom: 0">
                        <div style="padding-bottom: 5px">
                            <?= $value->lances ? preco($value->lances, 1) : '' ?>
                            <?php $lance += $value->lances ?>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            <tr>
                <td colspan="3" style="padding: 0; border-top: 0"></td>
            </tr>
            <tr>
                <td colspan="2" style="vertical-align: top;">
                    <?
                    $mysql->filtro = " WHERE  `tipo` = 'informacoes' AND lang = '" . LANG . "' ";
                    $info = $mysql->read_unico('configs');
                    ?>
                    <table cellpadding="0" cellspacing="0" border="0" style="width:100%;">
                        <tr>
                            <td style="width: 40px; vertical-align: top;">OBS.:</td>
                            <td><?= isset($_GET['emitir_nota_txt']) ? $_GET['emitir_nota_txt'] : '' ?></td>
                        </tr>
                    </table>
                </td>
                <td>
                    <table cellpadding="0" cellspacing="0" border="0" style="width:100%;">
                        <tr>
                            <td style="width: 100px"><b>SUB TOTAL</b></td>
                            <td><?= preco($lance, 1) ?></td>
                        </tr>
                        <tr>
                            <td style="width: 100px; padding-top: 5px"><b>COMISSÃO</b></td>
                            <td><?= preco(($lance * 5 / 100), 1) ?></td>
                        </tr>
                        <tr style="font-size: 16px">
                            <td style="width: 100px; padding-top: 5px"><b>TOTAL</b></td>
                            <td><b><?= preco($lance + ($lance * 5 / 100), 1) ?></b></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>









    <?php } elseif ($_GET['nome'] == 'etiqueta') { ?>
        <?php foreach ($lotes as $key => $value) { ?>
            <table cellpadding="0" cellspacing="0" border="1" style="width:100%; height: 500px;">
                <tr style="height: 120px;">
                    <td style="text-align: center; border-right: 0">
                        <div style="padding-top: 10px"><img src="<?= DIR_C ?>/web/img/z_leilao/logo.png" style="max-width:200px;"></div>
                    </td>
                    <td style="text-align: center; border-left: 0">
                        <div style="font-size:40px; font-weight:bold">LOTE: <?= (int) $value->ordem ?></div>
                        <div style="font-size:24px; font-weight:bold">LEILÃO: <?= rel('leiloes', $value->leiloes, 'codigo') ?></div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="padding: 10px; text-align: justify; vertical-align: top">
                        <b style="font-size: 16px">Descrição do lote:</b>
                        <div style="padding: 5px; padding-bottom: 0px; font-size: 14px"><?= txt($value) ?></div>
                    </td>
                </tr>
                <tr style="height: 80px;">
                    <td style="padding: 5px; font-size: 16px; text-align: center; border-right: 0">
                        <b>Data do leilão:</b> <?= data($value->data_ini, 'd/m/Y H:i') ?>
                    </td>
                    <td style="padding: 5px; font-size: 16px; text-align: center; border-left: 0">
                        <b>Lance inicial:</b> <?= preco($value->lance_ini, 1) ?>
                    </td>
                </tr>
                <tr style="height: 80px;">
                    <td colspan="2" style="padding: 5px; font-size: 16px; text-align: center;">
                        <b><?= DIR_C ?> | &#9742; <?= $info_termos_e_notas->telefone ?></b>
                    </td>
                </tr>
            </table>
            <div style="height: 20px"></div>
        <?php } ?>


    <?php } ?>

    </div>

<?php } else { ?>
    <?php $ids = isset($_GET['ids']) ? '?ids=' . $_GET['ids'] : '' ?>
    <?php location(DIR . '/login/' . $_GET['pg'] . '/' . $_GET['nome'] . '/' . $_GET['id'] . '/' . $ids); ?>
<?php } ?>

<?php } else { ?>
    Ação Não Permitida!<br>
    Esse Lote Não Foi Arrematado ou Não Foi Pago!
<?php } ?>