<div class="container-fluid">
    <section class="container p-3">

        <div class="centerr pt40 pb40">
            <div class="fz24 fwb ttu"><?= $item->nome ?><div class="w100 h5 bdw3 bdb_FF8C00"></div>
            </div>

            <div class="pt30 pb40">
                <?= txt($item) ?>
                <div class="h10 clear"></div>
                <?= rede() ?>
            </div>

            <?php if ($mais_fotos) { ?>
                <ul>
                    <?php foreach ($mais_fotos as $key => $value) { ?>
                        <?php $img->link = 1 ?>
                        <li class="wr3 pb30 tac"><?= $img->img($value, 200, 200) ?></li>
                        <?= clear($key, 4) ?>
                    <?php  } ?>
                    <div class="clear"></div>
                </ul>
            <?php  } ?>

        </div>

    </section>
</div>